### ISSUE TITLE
query vacancy のところの画面遷移変更依頼

### ISSUE THREAD

**Issue by yutopio** [hyurumi/8koma-client#111]
候補日時選定の時間が開いた瞬間に、Invite する対象者を最初に教えてもらいたい。たとえば、`/api/vacancy/start` とか呼んでほしい。そしたら候補日時の検索セッションを始める。

また同時に、画面が開いた当初は、朝とかの時間帯を選択していない状態にしておいてほしい。かわりに「希望の時間帯を選んでください」みたいなメッセージを出しておいてほしい。こうすることで、サーバが背後で Google Calendar に問い合わせる余裕を作れる。

いざ、時間帯を指定したりしたら、`/api/vacancy/query` みたいなのを呼ぶ。このとき、先の検索セッション キーも渡しておく。(本質的にはいらないかもしれないけど、将来的にセキュリティ面から、ユーザの空き状況を Brute-force で破られるのを防ぐための quota にするかも)

こうすると、`/api/vacancy/query` を呼ぶたびに Google Calendar へ伺わずに、早いキャッシュで答えることができるかも。

参照: https://github.com/yutopio/hachiko-server/issues/48

**Comment by daisy1754** [comment]
良いかも，ただがっつりAPI変わるのでやっぱり動画とるまで本番環境のコードはいじらないほうがいいかも．

**Comment by daisy1754** [comment]
クライアント的には，画面開いた瞬間に /startを叩けば良い，という感じぽい

**Comment by daisy1754** [comment]
https://github.com/yutopio/hachiko-server/issues/81
