### ISSUE TITLE
PlanCreateActivityをデザインする

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#12]
FireWorksで作ってみる。

**Comment by hyurumi** [comment]
カレンダーで日付を選択し、下のスライダーで時間帯を選択。
複数日付を同時に操作可能。
選んだ日時は最下部に表示、スワイプか長押しで削除かな。
カレンダーを公開設定している人は予定が入っているところは下のバーみたいに表示

![fireworls_stencil3](https://f.cloud.github.com/assets/427584/630327/eb981a94-d19e-11e2-8c3a-705e487ebff3.png)

**Comment by daisy1754** [comment]
一旦閉じるのすけ
