### ISSUE TITLE
検索バーが黒くちらつく

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#120]
検索バーに文字を入れたり消したりしてると，ListView再描画の際に背景が黒くちらつく
西浦Galaxy S4では起きないが，HTC firstでは起きる(´・ω・｀)

![fault](https://f.cloud.github.com/assets/980077/1378319/ce80db40-3ac5-11e3-9c9b-955c0b1f65ac.png)

**Comment by daisy1754** [comment]
ふと思いついて，ActivityのThemeをHolo.Lightに変えたら直った件
再描画時のデフォルト色，みたいな設定項目があるのだろうか？
hachiko.themeはHolo.Lightを継承してるはずなのに…継承とはなんだったのか

**Comment by hyurumi** [comment]
ごごご

**Comment by daisy1754** [comment]
style.xmlみるとHolo.Light継承してることになってたよ
背景を明示的にしていすることで，2箇所の黒いちらつきのうち目立つ方は治すことが出きた．下の変換候補が表示されてたとこにも黒いちらつきがあって，こっちはまあ自然な感じなので別にあってもいいんだけど，Holo.Lightだと起きない現象なので依然気になる

![partially_fixed](https://f.cloud.github.com/assets/980077/1378321/d635bd7e-3ac5-11e3-8bad-32591c24d2cf.png)

**Comment by daisy1754** [comment]
すみません，pushした直後にミスに気づいたので直してpush -fしまんた
2つあるのは，masterとreleaseというブランチを別々に育ててるからです．

依然下の黒くなるのは原因不明

**Comment by daisy1754** [comment]
上で議論した通り主要な問題は解決されてて，バグとは言えないレベルだと思うので閉じます
