### ISSUE TITLE
FriendList in MainActivityのデザイン

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#13]
Fireworksで。

**Comment by hyurumi** [comment]
コメントお願いします。
・通常表示の時は使われる順にでも表示、お気に入りは手動で登録しているもの。
・検索で文字を入力すると、自動で下の表示部分がうにょうにょ変化する。
・タップで選択。（長押しで何らかのメニュー（お気に入り登録・ブロックなど）を出そうかと思っている）
・誰かが選択されると画面下に今だれが選択されているかが表示される。
・だれが選択されているかの表示の右からOKでプラン詳細をつくる画面へ移行

![normal](https://f.cloud.github.com/assets/427584/564859/3fc461f0-c5af-11e2-9a3d-0e6aebfc3aac.png)
![when_some _friends_are_selected](https://f.cloud.github.com/assets/427584/564860/4009c1aa-c5af-11e2-9ed2-36304f34f4db.png)

**Comment by daisy1754** [comment]
電話帳から引っ張ってくるデータだと，アイコンが設定されていることが期待できないので，選択されたユーザ一覧のとこでは，アイコンの代わりに名前を出してあげたほうが良い？（Google Hangoutはまさにそんなかんじ)

**Comment by hyurumi** [comment]
うん、その質問は非常に悩ましいとこで、俺の認識としては、LINEやTwitterもそうだけど、使いこみはじめると、自分のアバターはわりと初心者ユーザーでも早い段階で設定する印象があって、大丈夫かなと思っているんだけど。
つまり、ここでのアイコンは
Hachikoユーザーでアイコンを登録している→アイコン表示
Hachikoユーザーでアイコンを登録していない→白いデフォルトアイコン
Hachikoユーザーではない→黒いデフォルトアイコン
ってかんじにしてみました。
どでしょかね？

**Comment by daisy1754** [comment]
将来的に世界のすべてがHachikoユーザになってアイコン設定してくれたらまあ良いとして，
そこにいたるまでに，Hachikoユーザじゃない人を三人くらい誘おうとするユースケースを考えると，
３人くらいポチポチ押して，招待画面にうつる前にもう一回誰選んだか確認しようとしたら，デフォルトアイコンが３つ並んでいるだけで，友達選ぶときに誤って隣とかタップしてても気付けない，ということよね？そんな不便をユーザに強いる必要はないのでは．

**Comment by hyurumi** [comment]
あ、ごめん勘違いしてた、検索画面のアイコン要らないという話かと思ってたｗ
そして、下のとこ名前つけ忘れた・・。下は名前のリストのが良いかねぇ・
そして、たしかにデフォルトアインこんが大量に並んでいるのは味気ないので検索画面もタイルじゃなくてリストのがいいかねぇ・・。

**Comment by hyurumi** [comment]
とりあえず下の表示をリストにしてみた。
![fireworls_stencil3](https://f.cloud.github.com/assets/427584/565030/963b94f4-c5d2-11e2-8fbb-eba8dff3819c.png)

**Comment by daisy1754** [comment]
一画面に表示出来るユーザ数があんまりへっちゃうとあれかなあとは思うけど，検索結果はタイルでも良いきがする．シャレオツ的な意味で．
選んだユーザのリストは，小さい文字だけで横に並べれないかしら．

**Comment by hyurumi** [comment]
こういうかんじ？
![fireworls_stencil3-1](https://f.cloud.github.com/assets/427584/565114/285c46f0-c5e0-11e2-9c30-91f28c84a30d.png)

**Comment by daisy1754** [comment]
いや，横一列に並べる，ということ
こんなかんじ×２（このスクショ撮るとき間違えて臼山をHangoutに誘ってしまった，すまそ）

![screenshot_2013-05-26-17-57-58](https://f.cloud.github.com/assets/980077/565121/d2967580-c5e2-11e2-84dc-8e487a09a2f6.png)
![screenshot_2013-05-26-17-59-30](https://f.cloud.github.com/assets/980077/565122/d4112824-c5e2-11e2-90db-14de9b6ae0f6.png)

**Comment by hyurumi** [comment]
うん、なるほど。
こんなかんじかな。
これ、複数人呼ぶと2人ぐらいしか同時には表示できなくて、
隠れているときは横のスワイプでみせるんだよね？
![fireworls_stencil3-2](https://f.cloud.github.com/assets/427584/565135/2f64c4cc-c5e5-11e2-834b-efb03c86526e.png)

**Comment by yutopio** [comment]
アバターの件は、初回起動時に一緒に撮らせればいいんでは。Mac ってそうでしょ、初回起動時にビルトイン カメラで撮って、ユーザ アカウントの写真になる。おなじように、初回起動で Gallery or Camera からアバターの設定させればよしかと。 (Skip できるようにもしとくけど) デフォルトは Gmail のアカウントの写真でもいいし。

Google みたいに
- 登録に使うメールア ドレスの確認
- 写真の設定
- アドレス帳のインポートの許可するか尋ねる
- You're almost done! Show my dashboard! みたいなー

写真で分からんときは、ビューの変更みたいなアイコンを作って、アイコンのグリッドにするか、アイコン + 名前のリスト表示にするか、選べるようにすれば？

**Comment by daisy1754** [comment]
タイル状のやつ実装してみた．masterにpushしてある．
![gridview](https://f.cloud.github.com/assets/980077/627223/e823f42e-d00d-11e2-9bfa-4ccb37d2b772.png)

あと，リスト状のやつが，[コミット f1e5217f5c579165951a8e5bc045eb5d09f26c99](https://github.com/usuyama/hachiko-client/commit/f1e5217f5c579165951a8e5bc045eb5d09f26c99)まで遡ればある
![listview](https://f.cloud.github.com/assets/980077/627224/18292446-d00e-11e2-9da8-96fccfdc22db.png)

現時点ですでに同じ人の名前を同定出来てない事例がいろいろある…

**Comment by daisy1754** [comment]
```
Hachikoユーザーでアイコンを登録していない→白いデフォルトアイコン
Hachikoユーザーではない→黒いデフォルトアイコン
```

といっていたけど，色変わるのは選択状態に使いたい気がするので，
二種類のデフォルトアイコンを使うのが良いのではないかしらん．
ち
なみに，今回使った，Androidの電話帳が使ってるアイコンは，直接使えるAPIはなく，Androidのエミュレータのファイル中から拾ってきた．なので，なんらかのライセンス的な縛りを受けるかもしれない．

**Comment by daisy1754** [comment]
push -fしてしまったので，この10分くらいの間にpullされた方がいたらご注意下されー

**Comment by hyurumi** [comment]
おぉ、すばらすぃ。
デフォルトアイコンはそうだね、複数必要だなぁ。
で、同じアイコンが勢ぞろいするのと、リストになるのとどっちがいいかねぇ。
Androidの電話帳のアイコンが使えないかもということであれば、
”登録に使うメールア ドレスの確認
写真の設定
アドレス帳のインポートの許可するか尋ねる
You're almost done! Show my dashboard! みたいなー”
のたけい戦略をつかえば同じアイコン勢揃い問題ともども解決はするね。

**Comment by yutopio** [comment]
まあ、アイコンが気になるなら、最初の選択を義務にさせちゃえばよいんでは。
1. 写真をギャラリーから選ぶ / カメラでその場で撮る。
2. [後で] を選択したら、アートっぽいアイコンをランダム配列 (? したら複数人でかぶりにくい) で表示、選択。

さすれば、どうやっても勝手にバラけるかも？

選択した状態がわかるかどうか、ってだけなのはもともと黒いアイコンの人だと、明るさを落としてもわかりにくいから、名前ラベルの背景色を青にするのも併用すべきかも。同じように、デフォルト アイコンは彩度が高いものを選ぶべきかも。まあ、適当案だけど。

**Comment by hyurumi** [comment]
友達リストをこっちのアイコンベース・フラット気味のやつでやってみた。
あと画像が揃うとこんなかんじか。
![fireworls_stencil2](https://f.cloud.github.com/assets/427584/628909/09384c6c-d10a-11e2-8bc7-d49507941c28.png)

**Comment by yutopio** [comment]
顔・・・笑。いいんじゃにあかしら？

**Comment by daisy1754** [comment]
一旦閉じるのすけ
