### ISSUE TITLE
Push を受け取ったことを確認する ACK を投げてほしい

### ISSUE THREAD

**Issue by yutopio** [hyurumi/8koma-client#134]
こうすることで、GCM に対して collapse されてもよいように、複数のプランをメッセージに載せられる。

**Comment by daisy1754** [comment]
これ，どうなんですかねー
too matchな気がしなくもないんですが，
結局ackを投げるとしても
- 携帯が圏外にあってackがすぐには届かない (pushは携帯が圏内に入った時gcmたんがちゃんと届けてくれる)
- pushは届いたがackのタイミングで通信エラー
  みたいなことはありますし

**Comment by yutopio** [comment]
ごめんなさいね。考え直したのですが、不要な気がしてきました。お騒がせしました。
