### ISSUE TITLE
選択せずにグループ作成を押せるタイミングがあっておしたらこんな感じに

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#136]
![2013-11-14 19 58 50](https://f.cloud.github.com/assets/427584/1548445/2711c1e6-4dc9-11e3-8b2a-9e788aa1b6ba.png)

**Comment by daisy1754** [comment]
（このissueに限らず）再現情報など可能な限り書いてくだされ

**Comment by hyurumi** [comment]
再現できない、また再現したらあける。
