### ISSUE TITLE
イベント作成時に全体用URLをクリップボードにコピーしておく。

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#149]

**Comment by yutopio** [comment]
このコミットの時点からすでに飛ぶようになっていた気がする。
https://github.com/yutopio/hachiko-server/commit/ad1add72f8d05d7ca08ff80e11e2d4e0848686ce

いままでのデータ構造に、token という文字列フィールドが増えています。
それをたとえば、 http://8koma.yutopio.net/respond/{{token}} みたいに文字列整形すれば OK

**Comment by daisy1754** [comment]
URLが間違っていた，あしたなおす
