### ISSUE TITLE
設定画面で候補日時の最大提示数を選べるように

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#159]

**Comment by yutopio** [comment]
これはサーバ側でも、一時期デモ用に、という意味で最大数 6 に固定しただけなので、Max いくつ、というのを変える用意はあります。ただ、どうやって API 化する？

**Comment by daisy1754** [comment]
vacancyのパラメタとして渡すのが自然ですかねえ？
設定同期用のAPIがあっても良いという話は別途ありましたが

**Comment by yutopio** [comment]
サーバ側では https://github.com/yutopio/hachiko-server/commit/a54db96bdfd92529fb1d2b36ef3a8fe1d0c74402 で実装済み
