### ISSUE TITLE
きまったよていリストのデザイン

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#16]
FireWorksで。

**Comment by hyurumi** [comment]
![fireworls_stencil](https://f.cloud.github.com/assets/427584/596138/15f07f34-cb69-11e2-9ed1-52e674875794.png)

**Comment by hyurumi** [comment]
左下のタブは
ノーティフィケーション・決まった予定リスト、友達リスト、設定、です。

**Comment by daisy1754** [comment]
https://github.com/usuyama/hachiko-client/issues/13
と一貫性があまり無い気がが
ナビゲーションバーは上か下かどっちかに統一したほうがいい気がする（俺は上に置く派です，iOSだと下にこういうの置くの普通やけどね
あと，設定については，Androidの慣例的には，2.3以前は端末に「設定」ボタンを載せるのが必須で，最近だとActionBarに載せるのが普通っぽい？(http://yuki312.blogspot.jp/2012/07/androidmenuactionbar.html)

**Comment by daisy1754** [comment]
どうでもいいけど，ふるみ，たけいで九十九里浜ドライブという予定にほっこりしたｗ

**Comment by hyurumi** [comment]
あ、ごめん一貫性がないのは、いろんなデザインをだしてどれが好きかのフィードバックを受けたくてｗ（個人的にはこっちのほうがまとまっていて気に入っています）
このデザインでは、ナビゲーションバーと名前が共存する場合、上で二段になるのは嫌なので下にしました。
で、中心となる機能を真ん中に置くのと、４より５のほうが見栄えがはるかにいいので設定を底においています。
あとすべての画面で決定、更新を右上に置きたかったのでせっていを下にした、というのもあります。

**Comment by hyurumi** [comment]
最終的にiosとAndroidを考えて、両方に展開しているアプリをいろいろ眺めていたら下のほうが人気なようだったのも理由の一つです。

**Comment by daisy1754** [comment]
一旦閉じるのすけ
