### ISSUE TITLE
回答画面がデフォルトで "?" に選択されているが、いかがなものか

### ISSUE THREAD

**Issue by yutopio** [hyurumi/8koma-client#162]
サーバ的には、"?" の選択と、未回答は別扱いになっている。ユーザが "?" が selected になっていてそれを放置していると、サーバ側はいつまでたっても回答がそろったと認識しない。

**Comment by daisy1754** [comment]
そうですねえ，古見と話しましたが，デフォルト全部"?"という回答がされたとして，それは果たして回答されたのだろうか，という感じはします．ホストとしては，少なくとも一つちゃんとyes/noを提示して欲しい気が．
ということで，クライアントとしては
1. デフォルトで全部?になっている
2. ひとつ以上の選択肢に対してyes/noを明示した時点でその人は回答したとみなす

という感じで行きたいのですが，どうでしょうか
