### ISSUE TITLE
アプリがアンインストールされたことをどうやって検知すればよいだろうか

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#17]
#### ACTION_PACKEAGE_REMOVEDシステムブロードキャスト

アプリが削除されたときに呼び出されるブロードキャスト．しかし，削除されるアプリ自身が聞くことはできない
#### GCM

http://developer.android.com/google/gcm/adv.html#unreg
によると，GCMでメッセージを届けようとして，そのときアプリが端末からアンインストールされていた場合
1. メッセージの送信は失敗する
2. 次回メッセージ送信時にはNotRegiteredが帰るらしい
しかし，1はすぐ返ってくる感じの通信ではなさそうな感じがする．

イベント招待のpushを送るごとに，ちゃんと送れたか確認する必要がある？

**Comment by yutopio** [comment]
http://stackoverflow.com/questions/6209730/is-it-possible-to-detect-android-app-uninstall
コレ見る限り、検出するすべはなさそう。
将来的な仕様変更に期待？

---

ガーン。。。化け化けで泣きそう。メール返信では UTF-8 に対応してないのか。
