### ISSUE TITLE
全てのPlanViewで予定をタップしたときに直近直後の予定を見れるようにする。

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#170]
UnfixedGuestViewの場合だけUIがある。
とりあえず、クライアントのカレンダーを使いサーバーのカレンダーとの違いは無視して良い。

**Comment by daisy1754** [comment]
この辺を参考にするよろし
https://github.com/hyurumi/8koma-client/commit/545647595fe8318cc7f8e1a1f373c39cfe02b3e2#diff-1e09e983ed0639896dac1f609c6f77d2R75
