### ISSUE TITLE
ユーザのつながり判定

### ISSUE THREAD

**Issue by yutopio** [hyurumi/8koma-client#18]
懸案のユーザのつながり判定。

要件
- なるべく、サーバに連絡帳をすべてアップロードするのは避けたい (かも？)。
- でも、あるユーザ A, B の連絡帳に、互いが載っていたら、A, B は友達と判断したい。
- ユーザの連絡帳の情報だけを見て、Hachiko ユーザか判断したい。

提案
- サーバでユーザの連絡先を把握したい (MapReduce で適当につながりが調べられる)。

疑問
- サーバ側から、ユーザの連絡先やカレンダーにアクセスする OAuth トークンは、どうすれば？

**Comment by daisy1754** [comment]
電話帳ぶっこ抜くのもありな気がしてきました．

クライアントアプリが電話帳データ，カレンダーデータを読む/書くには，適当なパーミッションを宣言すればよく，とくに認証は必要ありあません．
http://developer.android.com/reference/android/Manifest.permission.html#READ_CALENDAR

サーバからカレンダーに(直接)読み書きするには当然認証が必要だと思いますが，そのやりかたはよくわかりません．

**Comment by yutopio** [comment]
なるほど。ということは、やはりクライアント側から送信するしか方法はなさそう。サーバからやるためには、普通に OAuth やるしかない気がする。そうすると、どのくらいのデータをサーバに送らなければいけないのか、ということを考える必要がありそう。

電話機の連絡帳や、Facebook の友達など、それぞれのコンタクトが別々のフィールドの値を持っているはずだけど、最低限どれがマッチしていれば同一人物とみなす、というルール作りが必要だと思う。

サーバからクライアントに向けて送る、ユーザの同定をするための情報は最低限にしたいので (セキュリティ的都合と、クラウドの通信量的制約, サーバへの IN は無制限だけど、OUT は課金対象)、どの項目を使って同定するかを決めよう。

**Comment by yutopio** [comment]
LINE のケースでは電話番号が支配的になっているらしい。なので、↓ みたいな誤認ケースも大量に発生してるらしい。
http://matome.naver.jp/odai/2133103321519468601

やはりメール アドレスと電話番号のペアか？ Gmail なら、メール アドレスを変える人はあまりいないと信じて・・・。それから、端末から取得できる電話番号を信用できるとすれば、Gmail + Tel# のペアである程度、ユーザを追跡できるはず。Tel# が違うけど同じ Gmail の場合、複数端末を所持しているユーザとかも考えられるし。

ところで逆に、同じ Tel# だけど異なる Gmail が来た場合はどうしようか？

それから root 化した端末では Tel# 偽装できるし、そもそも生で API たたかれたら Tel# なんとでもなっちゃうのは、どうやって対策しようかしらん。本当ならここは LINE を見習って、SMS 送って認証できるようにしたい。

**Comment by hyurumi** [comment]
とりあえず当初の予定通り最初はなるたけシンプルに行きましょう。
詳細はまかせますけども。

**Comment by yutopio** [comment]
了解。

**Comment by daisy1754** [comment]
SMS送るのはざっとググった感じ結構たいへんそうでした．
Tel#偽装の件は，仮に一意なデバイスIDがとれる/作れるなら，Tel#の代りにデバイスIDを送れば良いですかね，将来的には．デバイスIDは容易には推測できないと信じたい．

**Comment by yutopio** [comment]
デバイス ID というと IMEI のこと？ 初回起動時にサーバに Register するとき、Unique な Access Token を発行する予定で、このトークンだけで個々の API の認証を可能にしようと思っている。お察しの通り、トークンはデバイスごとに発行するので、Android ならそのデバイス ID とサーバ側で紐づけておくし、コンピュータなら User Agent と IP などを使う。

Android API がどうやって REST を呼び出すかわからないけど、HTTPS のヘッダで Credential を乗せられるなら、そこにトークンを入れてもらう形で投げるのが、こちらとしては都合が良いかもしれない。

**Comment by daisy1754** [comment]
例えばSettings.Secure.ANDROID_IDは以下を返すらしいです．
A 64-bit number (as a hex string) that is randomly generated on the device's first boot and should remain constant for the lifetime of the device. (The value may change if a factory reset is performed on the device.)
ただ，これは書いてあるようにファクトリリセットでクリアされますし，他にもID系のAPIはいくつかあるみたいですが，実装依存的なのも結構あるっぽいです．

なので，サーバから一意なID振るほうがベターな気がします．
よくわかってないですけど，JavaなのでHTTPS通信とかはだいたい不自由なく出来るんじゃないでしょうか．

**Comment by daisy1754** [comment]
どうでも良いですが，Settings.Secure.ANDROID_IDは定義からして一意ではないですね…

**Comment by yutopio** [comment]
まあ、そもそも完璧に一意なものを得るのは、オープンソースたる Android では無理な気がしてきた。それこそ Gmail が PKI を提供していれば話は別だけど、そうでもなければどんな固有識別子を用意してあげても偽装可能な気がする。はてさて、ほかのアプリはどうやってデバイスの識別をしているんだろうか・・・。

ちなみに Java ならば、まあ適当にできるんじゃないでしょうか。Java to C# の interop ツールなんてのもたくさんあるから、平気な気がする。最悪、僕が C# on Azure から Java on GAE に移行すれば済む話っぽいし。

**Comment by usuyama** [comment]
うーん。思ったのですが、登録に関しては、
1. 登録なし(初回起動時発行のtokenのみ)
2. メール+password
を併用する形はどう？
ラインの場合も基本は電話番号(+token)で使えて便利だけども、アプリアンインストールとか機種変するとデータ消えてしまうし ( http://line.naver.jp/help/iphone/ja/serviceId/10155 )

我々も基本登録なしで使えて、追々、メール+password登録してもらうようにするのがいいんではないでしょうか？

![2013-05-23 10 56 06](https://f.cloud.github.com/assets/344133/552309/07fc2236-c34c-11e2-99ad-e0b6eae49e5b.jpg)

あと、サーバー側で自動的にhachiko userかどうか判定するって話だったけど、やはり難しいような気がする。これのせいで、コンタクトの表示も面倒にしている気がするし。

やっぱり、明示的に友達関係をhachiko platform上に作ってもらったほうがいいと思う。
もちろん、連絡帳upとかfb連携から友達関係うまい感じにsuggestして、なんなら自動追加も可能にしたい。

なので、アプリのfriend listでは、hachiko上の友達関係を優先表示する。それ以外の連絡帳にのっているメールアドレスが分かる人にも手軽に送れるようにしたい。さらに、line、fbだけでつながっている人も誘いたいから、doodleみたいにlink生成して手作業で送れるようにする。

とする方向がいいんじゃないかなと思っています。

というわけで二点提案で、
- ユーザー管理
  - 登録なし(初回起動時に発行のtoken。ローカルに保存)
  - mail+password
- 友達関係。hachiko userか判定
  - 明示的に

偽装という問題はあるけど、初回起動時にユーザーに入力してもらわなくても電話番号とgmailはとれる(?)と思うから、これ+電話帳upで友達関係のsuggestはうまくできそうじゃない？

と思ったのですが、どう思いますか？

**Comment by daisy1754** [comment]
ユーザ登録について：
おっしゃる通りかと．
ただ，その意見だとE-mail + Passを要求する理由が再インストールのためだけっぽいので，とりあえず登録機能は後で作れば良いような気がする．
友達関係についてはもうちょい考えます．

**Comment by daisy1754** [comment]
友達について：
hachikoユーザを優先表示，hachikoユーザであることを明示，ともに賛成
明示的な「友達関係」はややこしいのでなくて良い気がする（サーバ上では持つ必要があるのかもしれない）
結局友達のサジェストや検索をするために，名前やメールアドレスと特定ユーザをひもづける必要がある？と思っていて，そしたら電話帳にあるだけの情報をサーバにおくってhachikoユーザか判定するのと同じ気がする．

最初の電話帳アップロード時にサーバで誰がhachikoユーザか判定，その後も適宜更新するとして，hachikoユーザの名前の横にはhachikoアイコンが表示されてる，とかでどうかしら．
Google Hangoutのアプリのように，友達リストが２つにわかれていて
まず「仲良い友達一覧」，その下に「端末に保存された友達一覧」が並んでいて，仲良い友達一覧にはよく誘う人やhachikoユーザが優先的に表示させるイメージ
さらに検索バーがあって，端末にない友達も含めて検索出来るって感じかなあ

参考までにGoogle Hangoutの友だちリストはこんな感じ(徐はともかく，一度も連絡した記憶がない王くんがおすすめされてるのはよくわからない…）
![screenshot_2013-05-23-23-48-11](https://f.cloud.github.com/assets/980077/555164/d3923c16-c3b8-11e2-86ff-bca2882654d7.png)

**Comment by hyurumi** [comment]
ふむふむ。
大筋は臼山の方針でいい気がする。
Lineのすぐれているところは、
そもそも連絡を取らないような人はリストに載っていない。（知り合いかも？リストから明示的に移動しないと隠れてるんですよ。）←これが見落としがちだけど結構重要。
従って、だいたい100人ぐらいの中から相手を選べば良い。
加えて本名なので簡単に友人を同定できる。
といったところにあるので、
そこまで今までの議論の延長でつめられればおｋかと思う。

ユーザーの負担は最小限に。
相手選択して、詳細決めると、Hachikoユーザーとメールアドレスが分かる人には連絡が行って、あとは自動生成されたリンクを表示。おわりてなかんじで。。
(LINEの人関連部分＋Doodleスケジューリング部分) \* 1000 = Hachiko!

**Comment by yutopio** [comment]
まとめると
- 連絡帳はサーバにアップロード。
- サーバは勝手に連絡帳のマッチングを行なって、Hachiko ユーザ同士かどうかの同定を行い、クライアントに Hachiko ID を返す。マッチングの根拠には (個人ごとに固有であるはずの) メール アドレス, Facebook ID などの項目を使う。
- クライアントでは、頻繁にイベントを作る相手を上位に出す。また、連絡帳の人間が Hachiko ID を持っていたら、Hachiko ユーザであることを示すアイコンを表示。表示には極力、本名を利用。Hangout 的な検索ボックスもつけるべき？
- コンピュータ上でのインタフェースを使いたい場合は、パスワードを登録させる。

でよし？

**Comment by usuyama** [comment]
サーバーで正確にマッチングするというところがやはり難しそう...。確率は計算できそうだけど。
ユーザーに要求する手順は増えちゃうけど、ラインのように明示的に友達追加する手順が合った方がよさそう？(ライン同様、自動承認、自動追加もできる)

集めてきたいろんな情報から2人が友達な可能性を計算して、
確率がすごく高かったら自動で友達に追加、まあまあだったらサジェストをだすとかするのもいいかも知れない。

とおもったけど、たけいさんの言うように、mailとfb idは"示す先のユーザー"は変わんなそうだから、そこは自動追加でいいのかな。

なら、こっちも登録と一緒で、最初はメールアドレスからハチコーid紐付けて、後々手動でハチコー友達追加できる機能もつけるといいかな。

乱文すいません。

**Comment by yutopio** [comment]
日本語で OK... GitHub の日本語対応が望まれますな。臼山は Edit して読めるようにしといてもらえると助かります。

それで、正確なマッチングは別にそんなに難しいことは無いと思う。たとえば、MapReduce でメールアドレスのマッチングを実現したければ、サーバに上がってきた連絡帳の情報 (誰 ID の連絡帳に、誰のアドレスが載ってる) と、自分の情報 (自分はこのアドレスで、ID はこれ) をアドレスを key として reduce し、そこの ID の人たちをひとくくりにお互い友達だね、ってしてあげれば良くて。まあ MapReduce が 2 段あれば、ある ID の人の友達リストを正確に作れますわな。

もちろん、明示的に追加するフローを追加しても良くて、それは西浦が提案してた検索ボックスから任意のユーザを探せる、っていうので良いんじゃないかと。LINE とまったく一緒だよね、これ。

**Comment by hyurumi** [comment]
鋭意デザイン中。
臼山ｗｗｗ
LINEはそういう点でよくできとりますがな。
