### ISSUE TITLE
解答催促の実装

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#183]
サーバー側まち
- Demand (回答が遅いユーザーにはっぱかける)
- Remind (決まった予定が近づいたらお知らせする)

**Comment by hyurumi** [comment]
c8872d5 を消すとUI出現。

**Comment by yutopio** [comment]
未テストですが、サーバでもちゃんとした実装がされました。
https://github.com/yutopio/hachiko-server/commit/e9f2912735c1dfe6683ba3fe55165d456fddbc69
