### ISSUE TITLE
新規登録リクエスト

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#26]

**Comment by daisy1754** [comment]
自分の電話番号を取得
http://stackoverflow.com/questions/2480288/how-can-i-programmatically-obtain-the-number-of-the-android-phone-with-the-api

自分のprimary emailを取得
http://stackoverflow.com/questions/2112965/how-to-get-the-android-devices-primary-e-mail-address

**Comment by daisy1754** [comment]
3つ実装する必要
- 自分自身の情報を送るリクエス卜
- 電話帳を引っこ抜くリクエスト
- FBの連絡先を引っこ抜くリクエスト (ゆくゆくはサーバ側で処理だけど，ひとまずは）

**Comment by yutopio** [comment]
現状、
- **自分自身の情報を送るリクエス卜**  
  `POST /api/user` もしくは `POST /api/user/login` して、セッション チケットを API で発行。
- **電話帳を引っこ抜くリクエスト** と **FBの連絡先を引っこ抜くリクエスト** は同一  
  `POST /api/users` で、アドレス帳 (contact の配列) をアップロード。API からは、おのおののフレンドの Hachiko ID が return される。

**Comment by daisy1754** [comment]
おお，ありです
電話帳から取れるデータとFBから取れるデータはかなり隔たりがありそうなんですが，同じ配列でいいんですか？あと，会員番号特定以外の名寄せ処理（電話帳とFBの友人間の重複をまとめ）とかはやってもらえるのでしょうか？

**Comment by yutopio** [comment]
同じ配列でよくします。ただ、とれるデータが違うので、もってないフィールドは null にしておきます (というか JSON 的には、そのフィールドは省略)。基本的に Facebook ID が同一なら、同一人物という認定をするつもり。

名寄せは、別の Issue #18 と #28 、それから更新で #29 が関連しそう。別にスレッドたてるべきかも。

**Comment by daisy1754** [comment]
上での名寄せをやってもらえるのか，というのは， `/api/users`の挙動として，同一人物を表すデータが(電話帳，FBそれぞれから)入力に入ってしまったとして，出力時のHachikoIDはどうなるのか，という意味です．

**Comment by yutopio** [comment]
良い質問です。 `POST /api/users` の挙動では、異なるデータが入ってきた場合でも、名寄せのアルゴリズムが同一人物とみなせば、それらには同一の Hachiko ID が割り振られます。

**Comment by yutopio** [comment]
ちなみに、もっと具体的なイメージを使うための例としては、

``` json
[
  { "name": "Yuto Takei", "fbid": "1600221779" },
  { "name": "Yuto", "mobile": "09034270075" }
]
```

とかを POST された結果として、同一ユーザとみなせれば

``` javascript
[ 1001, 1001 ]
```

のような出力が返される予定です。
