### ISSUE TITLE
Hachikoとしての統一された連絡先リストをつくる

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#28]
名寄せ処理はサーバに任せたいけど，とりあえずこっちで作っても良いかも．
適切なデータ形式を定義して，sqliteに保存

いまは電話帳の連絡先一覧とFBの連絡先一覧が別になってて，なおかつデータを毎回フェッチしてるので，あまりいけてない

**Comment by yutopio** [comment]
ちなみに、個別の連絡先 (電話帳のも Facebook フレンドのも) に対して、app 側でメタデータを保持させることはできる？ 具体的には Hachiko ID を個々の連絡先にサーバが教えてあげるので、それを持っておいてほしいのだけど。

**Comment by daisy1754** [comment]
可能です．というか，今は電話帳から直接データひっぱったりFBと通信したりそれぞれしてるのですが，そのかわりにアプリ独自のローカルデータベースに連絡帳一覧を保持する，というのがこのissueです．なので，任意のデータが保存可能です．

**Comment by yutopio** [comment]
なるほど。そしたら、サーバがもってるアドレス帳のローカル コピーを持つことと等しいんだよね。つまり、この Issue の問題としては、
- 紐づいてる元の連絡先 or Facebook コンタクトに update がかかった場合、Hachiko の local contact list とどう sync させるか (名寄せ？ トラッキング？)
- サーバ側にその diff をどうやって伝えるのか

という 2 つの問題にわけられるのかしら。

**Comment by daisy1754** [comment]
このissueとしては「サーバがもってるアドレス帳のローカル コピー」を実現することに絞りたいです．つまりデータ形式をよしなに定義してそれに対応するデータベースアクセス用メソッドをつくり，電話帳のデータとか，サーバからやってくるHachikoIDをそこにしまう，というところまで．

コメントいただいたようなことはむしろ #29 かと

**Comment by daisy1754** [comment]
一応作った，ただlocalContactIdとHachikoIDの対応持つくらいのもので，実際のデータはcontactにある
