### ISSUE TITLE
予定タイムスロットリクエスト

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#30]
誰と予定をたてる，いつごろがいいか

**Comment by yutopio** [comment]
`POST /api/plans`

**Comment by yutopio** [comment]
これのリクエスト、どうやってやればいいだろう。
現時点では、目安の時刻とほしいウィンドウの長さを与えてるけど、
現実的にはもっときめ細かくシナリオ分けしないと、対応できないのは自明。
