### ISSUE TITLE
予定立てたいリクエスト

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#31]
誰となにがしたいみたいなリクエストをHachikoになげる，Hachikoサーバから他ユーザに招待状送信

**Comment by daisy1754** [comment]
#9とかぶってた

**Comment by yutopio** [comment]
POS /api/plans になるよてい。詳細は API doc 参照 (まだ更新してない)

**Comment by daisy1754** [comment]
エラー出ずに投げるとこまでは作った．あとはお願いしやんす
