### ISSUE TITLE
予定に関するpush通知受信・ローカルデータベース更新

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#33]

**Comment by daisy1754** [comment]
成約時はカレンダーも更新

**Comment by yutopio** [comment]
push 通知するときのフォーマットってどうしよう。
なんか適切なドキュメントの ref くだしあ。

**Comment by daisy1754** [comment]
ぼくもよくわかってないので調べますです

**Comment by daisy1754** [comment]
pushもJSONで良さそうです．
雰囲気的には

```
'Content-Type: application/json',
'Authorization: key=(APIキー)'
```

のヘッダをつけて，下のようなJSON送っていただければ

```
$data = array(
  'tag' => 'hoge',
  'body' => 'fuga'
);

$post_data = array(
  'registration_ids' => array($registration_id),
  'collapse_key' => 'Hachiko notification test',
  'data' => $data
);
```
- registration_idsが端末を通してGoogleに登録した時の番号
- collapse_keyが同じ種類のNotificationが複数来た時にひとつにまとめるためのkeyになる文字
- dataが送りたいJSON
  です．

https://github.com/usuyama/hachiko-client/wiki/GCM%E3%81%A7push

**Comment by yutopio** [comment]
すばらしい。簡単だ。
