### ISSUE TITLE
New Eventのとこでカレンダー表示

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#37]
いらなそうなものガシガシ削ったら画面のスペースが余ったので、カレンダー表示してもいいかも。月のカレンダーは公式でもあるし、ライブラリもいっぱいあるけど、数日のある時間帯の予定、みたいのをうまいこと表示するのは自分で作るしかないかしら。

**Comment by daisy1754** [comment]
月だとこのへんが使える
https://developer.android.com/reference/android/widget/CalendarView.html 
https://code.google.com/p/android-calendar-view/
https://github.com/roomorama/Caldroid

Weeklyとかでよさげなのは見つけられてない、かろうじてこれとか
http://stackoverflow.com/questions/9355747/how-can-i-create-a-weekly-calendar-view-for-an-android-honeycomb-application

**Comment by hyurumi** [comment]
そうだねえ、必要最低限なかれんだーはやはり確認の意味であるとよいかもしれない、、

東京大学　
情報理工学系研究科
コンピュータ科学専攻
古見元気

Furumi GenkiUser Interface Research Group - IGARASHI Laboratory.  
Computer Science
The University of Tokyo

**Comment by daisy1754** [comment]
ちな、いまはこんな感じ
![create_event](https://f.cloud.github.com/assets/980077/1230523/1f8e669a-27e0-11e3-9b06-083fbea25fa6.png)

**Comment by daisy1754** [comment]
カレンダーいれるとこんな感じ？
![create_event_with_cal](https://f.cloud.github.com/assets/980077/1230526/3694320c-27e0-11e3-94c8-596943b612d5.png)

**Comment by hyurumi** [comment]
日程それぞれを淡色背景にして、カレンダー上での表示と一致させよう。
どれがどれだかわからなくなるので。

**Comment by daisy1754** [comment]
良いアイディアやけど，Googleカレンダー上で表示されてる色が何色か取れるようなAPIがあるだろうか，ないのでは

**Comment by yutopio** [comment]
ある気がする。
https://github.com/yutopio/hachiko-server/blob/master/WebFrontEnd/Models/GoogleCalendarModel.cs#L98

**Comment by daisy1754** [comment]
:+1:

**Comment by daisy1754** [comment]
土台のレイアウトがだいぶかわっているので，一旦閉じまする
また必要性を議論するときに開けましょう
