### ISSUE TITLE
Googleのアクセストークンが認証切れた時の対応

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#73]
アクセストークンの有効期間は一時間しかないっぽい(´・ω・｀)
1. 今使ってる認証でrefresh tokenをどうにか手に入れることができる？　（できたら一番いいけど，前調べたときはわからず）
2. サーバが必要になったらpushして,裏側で認証 (よく考えたらこれが出来るかも要検証である)
3. Hachiko起動時にトークンが有効でなければトークン更新 (ユーザをブロック)
4. 一般的なOAuthにしちゃう（一度認証すればサーバ側でrefresh tokenを使って再認証できる)

**Comment by hyurumi** [comment]
最終的にはネイティブアプリ以外でも展開していくので、４ですかねぇ。
ただビデオのためには今の実装で言ってもいい気がする、

**Comment by yutopio** [comment]
現在は 2 を使う方針でいました。まだ Push 送ってないですけど。
