### ISSUE TITLE
google-play-serivices_libの場所が違和感のかまたり。

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#81]
android-validator: Suspicious module dependency hachiko-client -> google-play-services_lib: Android application module depends on other application module. Possibly, you should change type of module 'google-play-services_lib' to 'Library' or change the dependency scope to 'Provided'.

**Comment by hyurumi** [comment]
Jar で読み込ませているのだから、Moduleとして依存する必要ないっぽい？

**Comment by daisy1754** [comment]
そうかもわからぬ，moduleの依存外すといいかんじやね…

**Comment by daisy1754** [comment]
http://stackoverflow.com/questions/17960315/importing-google-play-services-lib-into-intellij-idea-12
このへん見たのですが，ようわからん，とりあえずはmoduleへの依存はずせば再インストールされなくなって幸せぽいすな…

**Comment by hyurumi** [comment]
処置はまかせますw
Pushとばなくなってもあれなので

**Comment by daisy1754** [comment]
たぶんgoogle_play_services_libへの依存外しちゃって大丈夫でしょう，という気がする，少なくとも開発中は．あとこの辺の設定はバージョン管理対象外なので，個々人が好きにやりませう.
リリース用apk作るときにどう設定すべきか，というのはそのとき考えませうｗ
