### ISSUE TITLE
push notificationをタップしてもそのプランに飛ばなくてかなしい。

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#82]

**Comment by daisy1754** [comment]
ひとつの予定詳細画面みたいなものが現状ないですからねえ
予定一覧画面に飛ぶ，かつ現状は予定を「作成された日順」でソートしてるので，一番上に対象の予定がくるはず

**Comment by daisy1754** [comment]
ひとつの予定だけ表示する画面，みたいのあったほうがいいかしら
UnfixedGuestPlanViewとか流用してつくるだけなら簡単にできると思うけれど

**Comment by hyurumi** [comment]
あれ、予定一覧画面に飛ばなかったので、このISSUEをたてますたw
こっちのみすかもたしかめる

**Comment by hyurumi** [comment]
再現できない、なぞw
