### ISSUE TITLE
友達一覧で友達をタップしたときのフィードッバクが遅い、

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#83]

**Comment by hyurumi** [comment]
OnclickじゃなくてOntouch(MotionEvent.ACTION_DOWN)のイベントで発火させた方がはやいようだ。以下の順でイベントが発火。
(1) OnTouchイベント (MotionEvent.ACTION_DOWN)
(2) OnLongClickイベント
(3) OnTouchイベント (MotionEvent.ACTION_UP)
(4) OnClickイベント
注) 長押しクリックでなく単なるクリックの場合, 2番目のOnLongClickイベントが省略される.

**Comment by daisy1754** [comment]
遅いってそういうことか，反応重い的なやつかとおもた
OnClickをOnTouchに変えるだけならすぐできるのでやります

**Comment by daisy1754** [comment]
別ブランチで軽く実装してみたけど，反応早すぎて違和感
https://github.com/usuyama/hachiko-client/commit/3c46bcafe7cab7bdc166c54281389fea25d87d28

Google Hangoutもクリックで選択っぽいし，クリックのが自然では．
特に長押しでオプションとか将来入れるなら，選択はクリックで発火すべきな気がする

**Comment by hyurumi** [comment]
ふむ、なるほど、ハングアウトより遅く感じるんだけど、それはなんでだろう

**Comment by hyurumi** [comment]
Focusで一旦色を変えるか。

**Comment by daisy1754** [comment]
嘘だった，hangoutはondownでフォーカスっぽい色にしてて，clickで選択か，
「ondownでフォーカス」ってListViewのデフォルト動作っぽいけど，どこでうわがいちゃったんだろうか
調査しやす

**Comment by hyurumi** [comment]
おれのせいやもわからぬ、
Androidちゃんはデザインあてるとなんかいろいろデフォルトの挙動まで変わる気もする

**Comment by daisy1754** [comment]
色がどうよっていうのはあるかもしれんけど一旦閉じまする
