### ISSUE TITLE
PlanActivityにタブを追加してUnfixedHostPlan, UnfixedGuesetPlan, FixedPlanを区別

### ISSUE THREAD

**Issue by hyurumi** [hyurumi/8koma-client#89]

**Comment by daisy1754** [comment]
実はこれは地味にめんどくさい
というのは，複数のListViewをScrollViewの中にいれる，とかやりはじめるとスクロールの取り合いになってバグる
一方で，ひとつのListViewにすると，ひとつのListViewは一種類のデータを格納する前提につくられており，別の種類のView加えるにはPlanAdapterのgetViewあたりをうまいこといじる必要

**Comment by hyurumi** [comment]
たしかになー、、
今のままだと結構混乱を招きそうだよねぇ。
いっそTabにして分けるべきか。

**Comment by hyurumi** [comment]
使うとしたらこんなのとかかねぇ
https://code.google.com/p/android-amazing-listview/

**Comment by daisy1754** [comment]
すいません，僕の説明が雑でありんした．めんどいけど出来るよ，という話で，あるべき姿を追求してくだしあ．頑張って実装します．今もすでにUnfixedHostPlanView, UnfixedGuestPlanView, FixedPlanView混じってるしね．

**Comment by hyurumi** [comment]
むしろ、TabViewにすべきやんのんなー

**Comment by hyurumi** [comment]
6c5009eでほとんどできたので一旦閉じる。
