### ISSUE TITLE
サーバの準備ができたらGoogleの認証方式を変更

### ISSUE THREAD

**Issue by daisy1754** [hyurumi/8koma-client#97]
https://developers.google.com/accounts/docs/CrossClientAuth#offlineAccess

クライアント側はそんなに変更なさそう？

**Comment by daisy1754** [comment]
https://github.com/yutopio/hachiko-server/issues/42

**Comment by yutopio** [comment]
https://github.com/yutopio/hachiko-server/commit/9c303edc444a43e9a98cd27e36b582279274bcd9
